##### Здадание 1.4
###### Используя метод вращений, найти собственные значения λ1, λ2, λ3 и собственные векторы h1, h2, h3 симметрических матриц с погрешностью э = 0.01 для [[8, 2, -1], [2, -5, -8], [-1, -8, -5]]

In [1]:
import numpy as np

def rotate(A, p, q, theta):
    c = np.cos(theta)
    s = np.sin(theta)

    A_rotated = np.copy(A)
    
    for i in range(len(A)):
        for j in range(len(A)):
            if i == p and j == p:
                A_rotated[p, p] = c * c * A[p, p] - 2 * c * s * A[p, q] + s * s * A[q, q]
            elif i == q and j == q:
                A_rotated[q, q] = s * s * A[p, p] + 2 * c * s * A[p, q] + c * c * A[q, q]
            elif i == p and j == q:
                A_rotated[p, q] = 0
            elif i == q and j == p:
                A_rotated[q, p] = 0
            elif i != p and i != q and j != p and j != q:
                A_rotated[i, j] = A[i, j]
    
    return A_rotated

def jacobi_method(A, epsilon=0.01):
    n = A.shape[0]
    V = np.eye(n) 
    A_curr = np.copy(A)

    while True:
        max_val = 0
        p, q = 0, 0
        for i in range(n):
            for j in range(i + 1, n):
                if abs(A_curr[i, j]) > max_val:
                    max_val = abs(A_curr[i, j])
                    p, q = i, j

        if max_val < epsilon:
            break

        if A_curr[q, q] == A_curr[p, p]:
            theta = np.pi / 4
        else:
            theta = 0.5 * np.arctan2(2 * A_curr[p, q], A_curr[q, q] - A_curr[p, p])

        A_curr = rotate(A_curr, p, q, theta)
        
        temp = np.eye(n)
        temp[p, p] = np.cos(theta)
        temp[p, q] = -np.sin(theta)
        temp[q, p] = np.sin(theta)
        temp[q, q] = np.cos(theta)
        
        V = V @ temp

    return np.diagonal(A_curr), V

    
A = np.array([[8, 2, -1], [2, -5, -8], [-1, -8, -5]])


eigenvalues, eigenvectors = jacobi_method(A)


print("Собственные значения:")
print(np.round(eigenvalues, 3))
print("Собственные векторы:")
print(np.round(eigenvectors, 3))

Собственные значения:
[-13   8   2]
Собственные векторы:
[[ 0.022 -0.944  0.33 ]
 [ 0.75   0.234  0.619]
 [-0.661  0.234  0.713]]
